# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6nYUyOabSo3lhooiVweSj0sbW2zrhqa
"""

!pip install streamlit
import pandas as pd
from datetime import datetime
import streamlit as st

# Configuración de la página
st.set_page_config(page_title="Consulta de Defensas", page_icon="🎓")

# Cargar los datos (ajusta la ruta según donde lo despliegues)
@st.cache_data
def load_data():
    return pd.read_excel('Separador en Python.xlsx', dtype={'CEDULA': str})

df = load_data()
df['FECHA SIMPLE'] = pd.to_datetime(df['FECHA SIMPLE'])

# Función de consulta
def consultar_defensa(cedula):
    estudiante = df[df['CEDULA'].str.strip() == cedula.strip()]

    if estudiante.empty:
        return None, "No se encontró ningún estudiante con esa cédula."

    datos = estudiante.iloc[0]
    hoy = datetime.now().strftime('%Y-%m-%d')
    fecha_defensa = datos['FECHA SIMPLE'].strftime('%Y-%m-%d')

    info = {
        'nombre': datos['APELLIDOS Y NOMBRES '],
        'opcion': datos['OPCION DE TITULACIÓN\nEX. COM./TIC/TT'],
        'fecha': datos['FECHA SIMPLE'].strftime('%d/%m/%Y'),
        'hora': datos['HORA'],
        'enlace': datos['ENLACES'],
        'hoy': fecha_defensa == hoy
    }

    return info, None

# Interfaz de usuario
st.title("🎓 Sistema de Consulta de Defensas de Titulación")

cedula = st.text_input("Ingrese su número de cédula (solo números):", max_chars=10)

if st.button("Consultar"):
    if cedula:
        info, error = consultar_defensa(cedula)

        if error:
            st.error(error)
        else:
            st.success("Información encontrada:")
            st.subheader(info['nombre'])
            st.write(f"**Opción de titulación:** {info['opcion']}")

            if info['hoy']:
                st.write(f"**Fecha de defensa:** {info['fecha']}")
                st.write(f"**Hora:** {info['hora']}")
                st.write(f"**Enlace:** [Click aquí]({info['enlace']})")
                st.balloons()
            else:
                st.warning(f"No tienes programada una defensa para hoy. Tu defensa es el {info['fecha']}")
    else:
        st.warning("Por favor ingrese su número de cédula")

st.markdown("---")
st.caption("Sistema de consulta de defensas - Universidad XYZ")